name: Tweet

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout code
        uses: actions/checkout@v2
      - name: Checkout game state
        uses: actions/checkout@v2
        with:
          ref: save
          path: data
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - name: Run game
        env:
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN_KEY: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        run: node index.js
      - name: Commit and push
        run: |-
          cd ./data
          git config user.name "Twitris"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
